### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by blauks** [FredrikAugust/jul-i-A4#1]
Can you translate the NPST link to spanish? I really want to join, but my lack of english and norwegian skills make it hard for me to find it. Thank you! (Sorry for my bad english)

**Comment by FredrikAugust** [comment]
yes (si) of course (por su puesto)!

**Comment by blauks** [comment]
Merci

**Comment by FredrikAugust** [comment]
hope you are happy now
thanks

// federico
